#!/sbin/busybox sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ -z $3 ]]; then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
fi

zzmoove_predef="0"
zzmoove_find=`grep "zzmoove_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

#echo "P: $zzmoove_predef"
#echo "F: $zzmoove_find"

if [[ ! -z $zzmoove_find ]]; then
  $zzmoove_predef = $zzmoove_find 
else
  edit_value zzmoove_predef "0"
fi

write_value() {
  #echo "W: $1-$2"
  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  #echo "E: $1-$2"

  g_find=`grep $1=.* $DEFAULT_PROFILE`
  
  #echo "G: $g_find"
  
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value sampling_rate $sampling_rate 
  edit_value sampling_down_factor $sampling_down_factor 
  edit_value up_threshold $up_threshold 
  edit_value down_threshold $down_threshold 
  edit_value ignore_nice_load $ignore_nice_load 
  edit_value freq_step $freq_step 
  edit_value smooth_up $smooth_up 
  edit_value freq_limit $freq_limit 
  edit_value fast_scaling $fast_scaling 
  edit_value up_threshold_hotplug1 $up_threshold_hotplug1 
  edit_value up_threshold_hotplug2 $up_threshold_hotplug2 
  edit_value up_threshold_hotplug3 $up_threshold_hotplug3 
  edit_value down_threshold_hotplug1 $down_threshold_hotplug1 
  edit_value down_threshold_hotplug2 $down_threshold_hotplug2 
  edit_value down_threshold_hotplug3 $down_threshold_hotplug3 
  edit_value sampling_rate_sleep_multiplier $sampling_rate_sleep_multiplier 
  edit_value down_threshold_sleep $down_threshold_sleep 
  edit_value up_threshold_sleep $up_threshold_sleep 
  edit_value smooth_up_sleep $smooth_up_sleep 
  edit_value hotplug_sleep $hotplug_sleep 
  edit_value freq_limit_sleep $freq_limit_sleep 
  edit_value freq_step_sleep $freq_step_sleep 
  edit_value fast_scaling_sleep $fast_scaling_sleep 
  edit_value zzmoove_predef $zzmoove_predef 

  echo $sampling_rate >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate
  echo $sampling_down_factor >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_down_factor
  echo $up_threshold >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold
  echo $down_threshold >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold
  echo $ignore_nice_load >/sys/devices/system/cpu/cpufreq/zzmoove/ignore_nice_load
  echo $freq_step >/sys/devices/system/cpu/cpufreq/zzmoove/freq_step
  echo $smooth_up >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up
  echo $freq_limit >/sys/devices/system/cpu/cpufreq/zzmoove/freq_limit
  echo $fast_scaling >/sys/devices/system/cpu/cpufreq/zzmoove/fast_scaling
  echo $up_threshold_hotplug1 >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug1
  echo $up_threshold_hotplug2 >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug2
  echo $up_threshold_hotplug3 >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug3
  echo $down_threshold_hotplug1 >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug1
  echo $down_threshold_hotplug2 >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug2
  echo $down_threshold_hotplug3 >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug3
  echo $sampling_rate_sleep_multiplier >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate_sleep_multiplier
  echo $down_threshold_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_sleep
  echo $up_threshold_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_sleep
  echo $smooth_up_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up_sleep
  echo $hotplug_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/hotplug_sleep
  echo $freq_limit_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/freq_limit_sleep
  echo $freq_step_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/freq_step_sleep
  echo $fast_scaling_sleep >/sys/devices/system/cpu/cpufreq/zzmoove/fast_scaling_sleep
}

case "$zzpredef" in
  0)
    sampling_rate="100000"
    sampling_down_factor="4"
    up_threshold="70"
    up_threshold_hotplug1="68"
    up_threshold_hotplug2="68"
    up_threshold_hotplug3="68"
    down_threshold="52"
    down_threshold_hotplug1="55"
    down_threshold_hotplug2="55"
    down_threshold_hotplug3="55"
    ignore_nice_load="0"
    freq_step="5"
    freq_step_sleep="1"
    smooth_up="75"
    smooth_up_sleep="100"
    sampling_rate_sleep_multiplier="2"
    up_threshold_sleep="100"
    down_threshold_sleep="60"
    hotplug_sleep="1"
    freq_limit="0"
    freq_limit_sleep="800000"
    fast_scaling="0"
    fast_scaling_sleep="0"
    zzmoove_predef="0"
    write_values
    ;;
  1)
    sampling_rate="100000"
    sampling_down_factor="4"
    up_threshold="70"
    up_threshold_hotplug1="68"
    up_threshold_hotplug2="68"
    up_threshold_hotplug3="68"
    down_threshold="52"
    down_threshold_hotplug1="55"
    down_threshold_hotplug2="55"
    down_threshold_hotplug3="55"
    ignore_nice_load="0"
    freq_step="5"
    freq_step_sleep="1"
    smooth_up="75"
    smooth_up_sleep="100"
    sampling_rate_sleep_multiplier="2"
    up_threshold_sleep="100"
    down_threshold_sleep="60"
    hotplug_sleep="1"
    freq_limit="0"
    freq_limit_sleep="800000"
    fast_scaling="1"
    fast_scaling_sleep="1"
    zzmoove_predef="1"
    write_values
    ;;
  2)
    sampling_rate="120000"
    sampling_down_factor="1"
    up_threshold="95"
    down_threshold="40"
    ignore_nice_load="0"
    freq_step="10"
    smooth_up="75"
    freq_limit="0"
    fast_scaling="0"
    up_threshold_hotplug1="50"
    up_threshold_hotplug2="70"
    up_threshold_hotplug3="98"
    down_threshold_hotplug1="35"
    down_threshold_hotplug2="45"
    down_threshold_hotplug3="65"
    sampling_rate_sleep_multiplier="2"
    down_threshold_sleep="60"
    up_threshold_sleep="100"
    smooth_up_sleep="100"
    hotplug_sleep="1"
    freq_limit_sleep="800000"
    freq_step_sleep="1"
    fast_scaling_sleep="0"
    zzmoove_predef="2"
    write_values
    ;;
  3)
    sampling_rate="120000"
    sampling_down_factor="1"
    up_threshold="95"
    down_threshold="40"
    ignore_nice_load="0"
    freq_step="10"
    smooth_up="75"
    freq_limit="0"
    fast_scaling="1"
    up_threshold_hotplug1="50"
    up_threshold_hotplug2="70"
    up_threshold_hotplug3="98"
    down_threshold_hotplug1="35"
    down_threshold_hotplug2="45"
    down_threshold_hotplug3="65"
    sampling_rate_sleep_multiplier="2"
    down_threshold_sleep="60"
    up_threshold_sleep="100"
    smooth_up_sleep="100"
    hotplug_sleep="1"
    freq_limit_sleep="800000"
    freq_step_sleep="1"
    fast_scaling_sleep="1"
    zzmoove_predef="3"
    write_values
    ;;
  4)
    sampling_rate="45000"
    sampling_down_factor="1"
    up_threshold="67"
    down_threshold="52"
    ignore_nice_load="0"
    freq_step="5"
    smooth_up="75"
    freq_limit="0"
    fast_scaling="0"
    up_threshold_hotplug1="68"
    up_threshold_hotplug2="78"
    up_threshold_hotplug3="88"
    down_threshold_hotplug1="45"
    down_threshold_hotplug2="55"
    down_threshold_hotplug3="65"
    sampling_rate_sleep_multiplier="2"
    down_threshold_sleep="60"
    up_threshold_sleep="100"
    smooth_up_sleep="100"
    hotplug_sleep="1"
    freq_limit_sleep="800000"
    freq_step_sleep="1"
    fast_scaling_sleep="0"
    zzmoove_predef="4"
    write_values
    ;;
  5)
    sampling_rate="45000"
    sampling_down_factor="1"
    up_threshold="67"
    down_threshold="52"
    ignore_nice_load="0"
    freq_step="5"
    smooth_up="75"
    freq_limit="0"
    fast_scaling="1"
    up_threshold_hotplug1="68"
    up_threshold_hotplug2="78"
    up_threshold_hotplug3="88"
    down_threshold_hotplug1="45"
    down_threshold_hotplug2="55"
    down_threshold_hotplug3="65"
    sampling_rate_sleep_multiplier="2"
    down_threshold_sleep="60"
    up_threshold_sleep="100"
    smooth_up_sleep="100"
    hotplug_sleep="1"
    freq_limit_sleep="800000"
    freq_step_sleep="1"
    fast_scaling_sleep="1"
    zzmoove_predef="5"
    write_values
    ;;
  6)
    sampling_rate="40000"
    sampling_down_factor="1"
    up_threshold="60"
    down_threshold="20"
    ignore_nice_load="0"
    freq_step="25"
    smooth_up="70"
    freq_limit="0"
    fast_scaling="0"
    up_threshold_hotplug1="65"
    up_threshold_hotplug2="75"
    up_threshold_hotplug3="85"
    down_threshold_hotplug1="25"
    down_threshold_hotplug2="35"
    down_threshold_hotplug3="45"
    sampling_rate_sleep_multiplier="2"
    down_threshold_sleep="60"
    up_threshold_sleep="100"
    smooth_up_sleep="100"
    hotplug_sleep="1"
    freq_limit_sleep="800000"
    freq_step_sleep="1"
    fast_scaling_sleep="0"
    zzmoove_predef="6"
    write_values
    ;;
  7)
    sampling_rate="40000"
    sampling_down_factor="1"
    up_threshold="60"
    down_threshold="20"
    ignore_nice_load="0"
    freq_step="25"
    smooth_up="70"
    freq_limit="0"
    fast_scaling="1"
    up_threshold_hotplug1="65"
    up_threshold_hotplug2="75"
    up_threshold_hotplug3="85"
    down_threshold_hotplug1="25"
    down_threshold_hotplug2="35"
    down_threshold_hotplug3="45"
    sampling_rate_sleep_multiplier="2"
    down_threshold_sleep="60"
    up_threshold_sleep="100"
    smooth_up_sleep="100"
    hotplug_sleep="1"
    freq_limit_sleep="800000"
    freq_step_sleep="1"
    fast_scaling_sleep="1"
    zzmoove_predef="7"
    write_values
    ;;
esac;

eval echo $zzmoove_predef